import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

function supabase() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );
}

export async function GET(req: NextRequest) {
  const { searchParams } = req.nextUrl;
  const year = searchParams.get("year");
  const month = searchParams.get("month");

  const db = supabase();
  let query = db
    .from("episodes")
    .select("*")
    .in("grade", ["GREEN", "YELLOW"])
    .order("date", { ascending: true });

  if (year && month) {
    const paddedMonth = month.padStart(2, "0");
    query = query
      .gte("date", `${year}-${paddedMonth}-01`)
      .lte("date", `${year}-${paddedMonth}-31`);
  }

  const { data, error } = await query;
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });

  const episodes = data ?? [];
  const title = year && month
    ? `Bright Spark — ${new Date(parseInt(year), parseInt(month) - 1).toLocaleString("default", { month: "long", year: "numeric" })}`
    : "Bright Spark — All Approved Episodes";

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>
    body { font-family: Arial, sans-serif; font-size: 11pt; max-width: 700px; margin: 40px auto; color: #222; }
    h1 { font-size: 18pt; border-bottom: 2pt solid #333; padding-bottom: 8px; margin-bottom: 24px; }
    .episode { margin-bottom: 40px; page-break-inside: avoid; }
    .episode-header { display: flex; align-items: baseline; gap: 12px; margin-bottom: 6px; }
    .date { font-size: 9pt; color: #888; font-family: monospace; }
    .category { font-size: 13pt; font-weight: bold; }
    .fun-badge { background: #e9d5ff; color: #6b21a8; border-radius: 4px; padding: 1px 6px; font-size: 9pt; }
    .subcategory { font-size: 11pt; color: #555; }
    .difficulty { font-size: 9pt; padding: 1px 6px; border-radius: 4px; font-weight: bold; }
    .diff-easy { background: #dcfce7; color: #166534; }
    .diff-medium { background: #fef9c3; color: #854d0e; }
    .diff-hard { background: #fee2e2; color: #991b1b; }
    .qa { margin: 8px 0 12px; }
    .qa-q { margin-bottom: 4px; }
    .qa-a { font-weight: bold; }
    .script-section { margin-top: 12px; }
    .script-heading { font-size: 9pt; color: #888; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 6px; }
    .track { margin: 4px 0; font-size: 10pt; }
    .track-num { font-weight: bold; color: #888; margin-right: 6px; }
    .music-cue { color: #aaa; font-style: italic; }
    hr { border: none; border-top: 1px solid #e5e7eb; margin: 32px 0; }
  </style>
</head>
<body>
<h1>${title}</h1>
<p style="font-size:9pt;color:#888;margin-bottom:32px;">Generated by Bright Spark · ${episodes.length} approved episodes · ${new Date().toLocaleDateString()}</p>

${episodes.map((ep, idx) => {
  const tracks: Array<{ trackId: number; label: string; content: string; isMusicCue?: boolean }> = ep.script_json ?? [];
  const diffClass = ep.difficulty === "Easy" ? "diff-easy" : ep.difficulty === "Medium" ? "diff-medium" : "diff-hard";
  return `<div class="episode">
  <div class="episode-header">
    <span class="date">${ep.date} · ${ep.day_of_week}</span>
    ${ep.is_fun_day ? '<span class="fun-badge">🎉 Fun Observance Day</span>' : `<span class="category">${ep.category}</span>`}
    <span class="subcategory">${ep.subcategory}</span>
    <span class="difficulty ${diffClass}">${ep.difficulty}</span>
  </div>
  <div class="qa">
    <div class="qa-q"><strong>Q:</strong> ${ep.question}</div>
    <div class="qa-a">A: ${ep.answer}</div>
  </div>
  <div class="script-section">
    <div class="script-heading">Script</div>
    ${tracks.map(t => `<div class="track"><span class="track-num">${t.trackId}.</span>${t.isMusicCue ? `<span class="music-cue">${t.content}</span>` : t.content}</div>`).join("")}
  </div>
  ${idx < episodes.length - 1 ? "<hr>" : ""}
</div>`;
}).join("\n")}

</body>
</html>`;

  const filename = year && month
    ? `bright-spark-${year}-${month.padStart(2, "0")}.html`
    : "bright-spark-all.html";

  return new Response(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}
